a = input('Digite algo aqui: ')
print('O tipo primitivo desse valor é', type(a))
print('So tem espaços:', a.isspace())
print('É um número: ', a.isnumeric())
print('É um alfabeto: ', a.isalpha())
print('É alphanumerico: ', a.isalnum())
print('Esta em MAISCULA: ', a.isupper())
print('Esta em minuscula: ', a.islower())
print('Esta capitalizada: ', a.istitle())
